<?php

return array(
    [
        "author" => "Chinua Achebe",
        "country" => "Nigeria",
        "imageLink" => "$host/img/things-fall-apart.jpg",
        "language" => "English",
        "link" => " https://en.wikipedia.org/wiki/Things_Fall_Apart",
        "pages" => 209,
        "title" => "Things Fall Apart",
        "year" => 1958,
        "price" => 54.77,
    ],
    [
        "author" => "Hans Christian Andersen",
        "country" => "Denmark",
        "imageLink" => "$host/img/fairy-tales.jpg",
        "language" => "Danish",
        "link" => " https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.",
        "pages" => 784,
        "title" => "Fairy tales",
        "year" => 1836,
        "price" => 10,
    ],
    [
        "author" => "Dante Alighieri",
        "country" => "Italy",
        "imageLink" => "$host/img/the-divine-comedy.jpg",
        "language" => "Italian",
        "link" => " https://en.wikipedia.org/wiki/Divine_Comedy",
        "pages" => 928,
        "title" => "The Divine Comedy",
        "year" => 1315,
        "price" => 112,
    ],
    [
        "author" => "Unknown",
        "country" => "Sumer and Akkadian Empire",
        "imageLink" => "$host/img/the-epic-of-gilgamesh.jpg",
        "language" => "Akkadian",
        "link" => " https://en.wikipedia.org/wiki/Epic_of_Gilgamesh",
        "pages" => 160,
        "title" => "The Epic Of Gilgamesh",
        "year" => 1700,
        "price" => 150,
    ],
    [
        "author" => "Unknown",
        "country" => "Achaemenid Empire",
        "imageLink" => "$host/img/the-book-of-job.jpg",
        "language" => "Hebrew",
        "link" => " https://en.wikipedia.org/wiki/Book_of_Job",
        "pages" => 176,
        "title" => "The Book Of Job",
        "year" => 600,
        "price" => 15,
    ],
    [
        "author" => "Unknown",
        "country" => "India/Iran/Iraq/Egypt/Tajikistan",
        "imageLink" => "$host/img/one-thousand-and-one-nights.jpg",
        "language" => "Arabic",
        "link" => " https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights",
        "pages" => 288,
        "title" => "One Thousand and One Nights",
        "year" => 1200,
        "price" => 45,
    ],
    [
        "author" => "Unknown",
        "country" => "Iceland",
        "imageLink" => "$host/img/njals-saga.jpg",
        "language" => "Old Norse",
        "link" => " https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga",
        "pages" => 384,
        "title" => "Nj\u00e1l's Saga",
        "year" => 1350,
        "price" => 87,
    ],
    [
        "author" => "Jane Austen",
        "country" => "United Kingdom",
        "imageLink" => "$host/img/pride-and-prejudice.jpg",
        "language" => "English",
        "link" => " https://en.wikipedia.org/wiki/Pride_and_Prejudice",
        "pages" => 226,
        "title" => "Pride and Prejudice",
        "year" => 1813,
        "price" => 40,
    ],
    [
        "author" => "Honor` de Balzac",
        "country" => "France",
        "imageLink" => "$host/img/le-pere-goriot.jpg",
        "language" => "French",
        "link" => " https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot",
        "pages" => 443,
        "title" => "Le P`re Goriot",
        "year" => 1835,
        "price" => 111,
    ],
    [
        "author" => "Samuel Beckett",
        "country" => "Republic of Ireland",
        "imageLink" => "$host/img/molloy-malone-dies-the-unnamable.jpg",
        "language" => "French, English",
        "link" => " https://en.wikipedia.org/wiki/Molloy_(novel)",
        "pages" => 256,
        "title" => "Molloy, Malone Dies, The Unnamable, the trilogy",
        "year" => 1952,
        "price" => 40,
    ],
    [
        "author" => "Giovanni Boccaccio",
        "country" => "Italy",
        "imageLink" => "$host/img/the-decameron.jpg",
        "language" => "Italian",
        "link" => " https://en.wikipedia.org/wiki/The_Decameron",
        "pages" => 1024,
        "title" => "The Decameron",
        "year" => 1351,
        "price" => 31,
    ],
    [
        "author" => "Jorge Luis Borges",
        "country" => "Argentina",
        "imageLink" => "$host/img/ficciones.jpg",
        "language" => "Spanish",
        "link" => " https://en.wikipedia.org/wiki/Ficciones",
        "pages" => 224,
        "title" => "Ficciones",
        "year" => 1965,
        "price" => 88,
    ],
    [
        "author" => "Emily Bront",
        "country" => "United Kingdom",
        "imageLink" => "$host/img/wuthering-heights.jpg",
        "language" => "English",
        "link" => " https://en.wikipedia.org/wiki/Wuthering_Heights",
        "pages" => 342,
        "title" => "Wuthering Heights",
        "year" => 1847,
        "price" => 50,
    ],
    [
        "author" => "Albert Camus",
        "country" => "Algeria, French Empire",
        "imageLink" => "$host/img/l-etranger.jpg",
        "language" => "French",
        "link" => " https://en.wikipedia.org/wiki/The_Stranger_(novel)",
        "pages" => 185,
        "title" => "The Stranger",
        "year" => 1942,
        "price" => 25,
    ],
    [
        "author" => "Paul Celan",
        "country" => "Romania, France",
        "imageLink" => "$host/img/poems-paul-celan.jpg",
        "language" => "German",
        "link" => "",
        "pages" => 320,
        "title" => "Poems",
        "year" => 1952,
        "price" => 90,
    ],
    [
        "author" => "Louis-Ferdinand C`line",
        "country" => "France",
        "imageLink" => "$host/img/voyage-au-bout-de-la-nuit.jpg",
        "language" => "French",
        "link" => " https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night",
        "pages" => 505,
        "title" => "Journey to the End of the Night",
        "year" => 1932,
        "price" => 60,
    ],
    [
        "author" => "Miguel de Cervantes",
        "country" => "Spain",
        "imageLink" => "$host/img/don-quijote-de-la-mancha.jpg",
        "language" => "Spanish",
        "link" => " https://en.wikipedia.org/wiki/Don_Quixote",
        "pages" => 1056,
        "title" => "Don Quijote De La Mancha",
        "year" => 1610,
        "price" => 30,
    ],
    [
        "author" => "Geoffrey Chaucer",
        "country" => "England",
        "imageLink" => "$host/img/the-canterbury-tales.jpg",
        "language" => "English",
        "link" => " https://en.wikipedia.org/wiki/The_Canterbury_Tales",
        "pages" => 544,
        "title" => "The Canterbury Tales",
        "year" => 1450,
        "price" => 100,
    ],
    [
        "author" => "Anton Chekhov",
        "country" => "Russia",
        "imageLink" => "$host/img/stories-of-anton-chekhov.jpg",
        "language" => "Russian",
        "link" => " https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov",
        "pages" => 194,
        "title" => "Stories",
        "year" => 1886,
        "price" => 15,
    ],
    [
        "author" => "Joseph Conrad",
        "country" => "United Kingdom",
        "imageLink" => "$host/img/nostromo.jpg",
        "language" => "English",
        "link" => " https://en.wikipedia.org/wiki/Nostromo",
        "pages" => 320,
        "title" => "Nostromo",
        "year" => 1904,
        "price" => 45,
    ],
    [
        "author" => "Charles Dickens",
        "country" => "United Kingdom",
        "imageLink" => "$host/img/great-expectations.jpg",
        "language" => "English",
        "link" => " https://en.wikipedia.org/wiki/Great_Expectations",
        "pages" => 194,
        "title" => "Great Expectations",
        "year" => 1861,
        "price" => 38,
    ],
    [
        "author" => "Denis Diderot",
        "country" => "France",
        "imageLink" => "$host/img/jacques-the-fatalist.jpg",
        "language" => "French",
        "link" => " https://en.wikipedia.org/wiki/Jacques_the_Fatalist",
        "pages" => 596,
        "title" => "Jacques the Fatalist",
        "year" => 1796,
        "price" => 90,
    ],
    [
        "author" => "Alfred D\u00f6blin",
        "country" => "Germany",
        "imageLink" => "$host/img/berlin-alexanderplatz.jpg",
        "language" => "German",
        "link" => " https://en.wikipedia.org/wiki/Berlin_Alexanderplatz",
        "pages" => 600,
        "title" => "Berlin Alexanderplatz",
        "year" => 1929,
        "price" => 60,
    ],
    [
        "author" => "Fyodor Dostoevsky",
        "country" => "Russia",
        "imageLink" => "$host/img/crime-and-punishment.jpg",
        "language" => "Russian",
        "link" => " https://en.wikipedia.org/wiki/Crime_and_Punishment",
        "pages" => 551,
        "title" => "Crime and Punishment",
        "year" => 1866,
        "price" => 75,
    ],
    [
        "author" => "Fyodor Dostoevsky",
        "country" => "Russia",
        "imageLink" => "$host/img/the-idiot.jpg",
        "language" => "Russian",
        "link" => " https://en.wikipedia.org/wiki/The_Idiot",
        "pages" => 656,
        "title" => "The Idiot",
        "year" => 1869,
        "price" => 59,
    ],
);
